#template: Hello, %s!

#defaultName: ${DW_DEFAULT_NAME:-Stranger}

logging:
  level: INFO
  loggers:
    com.users.app: DEBUG
    
mongoHost : localhost
mongoPort : 27017
mongoDB : users
collectionName: users

influxHost: http://localhost:8086
influxDataBase: logs    