logging:
  level: INFO
   
  appenders:
    - type: console
      threshold: ALL
      timeZone: IST
       
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
      port: 4000
      type: http
 
mongoHost : localhost
mongoPort : 27017
mongoDB : kudos
collectionName: kudos

influxHost: http://localhost:8086
influxDataBase: logs

#cassandra:
#  clusterName: "kudos"
#  keyspace: "kudos"
#  contactPoints: ["127.0.0.1"]
#  port: 9042
  
cassandraContactPoint: 127.0.0.1
cassandraPort: 9042
cassandraKeyspace: kudos
